name: Test DevOps360 Terraform Files

on:
  push:
    branches: 
      - developers
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: |
            terraform/envs/dev/.terraform
            terraform/envs/dev/.terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/envs/dev/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Install tf-summarize
        uses: kishaningithub/setup-tf-summarize@v1

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Terraform init
        working-directory: terraform/envs/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform plan -no-color -input=false -lock-timeout=5m -out=tfplan
      
      - name: Summarize plan
        run: |
          cd terraform/envs/dev
          terraform show -json tfplan > tfplan.json
          tf-summarize tfplan > summary.txt

      - name: Upload summary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-summary
          path: terraform/envs/dev/summary.txt


        